name: Build

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2    
    - uses: actions/checkout@v2
    
    - name: NuGet PKG Restore
      run: msbuild -t:restore RanorexOrangebeardListener.sln
    
    - name: Build
      run: msbuild RanorexOrangebeardListener.sln

    # Ranorex Listener doesn't have unit tests at this point.      
    #- name: Run Tests
    #  run: vstest.console.exe .\tests\RanorexOrangebeardListener.Tests\bin\Release\RanorexOrangebeardListener.Tests.dll