name: Tag and Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write  # required for NuGet Trusted Publishing (OIDC token issuance)
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - uses: actions/checkout@v2

      - name: Checkout Ranorex DLLs
        uses: actions/checkout@v4
        with:
          repository: orangebeard-io/rx-libs
          token: ${{ secrets.RX_LIBS_TOKEN }}
          path: rxLibs

      - name: Bump versions
        uses: mediatech15/dotnet-bump-version-action@v1.0.2
        with:
          version_files: "RanorexOrangebeardListener.csproj"
          bump: "minor"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version info
        uses: naminodarie/get-net-sdk-project-versions-action@v2
        id: get-version
        with:
          proj-path: RanorexOrangebeardListener.csproj

      - name: NuGet PKG Restore
        run: msbuild -t:restore RanorexOrangebeardListener.sln

      - name: Build
        run: msbuild RanorexOrangebeardListener.csproj /p:Configuration=Release /p:NoWarn=1591

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: bin\Release
          filename: 'release_artifacts.zip'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.assembly-version }}
          release_name: Release ${{ steps.get-version.outputs.assembly-version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_artifacts.zip
          asset_name: release_artifacts.zip
          asset_content_type: application/zip

      - name: NuGet login (OIDC -> temporary API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish to NuGet
        run: dotnet nuget push bin\Release\*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
